version: "3.8"

services:
  postgres_db:
    container_name: core_pg_db
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=${MASTER_DB_USER}
      - POSTGRES_PASSWORD=${MASTER_DB_PASSWORD}
      - POSTGRES_DB=${MASTER_DB_NAME}
    volumes:
      - prod_postgres_data:/var/lib/postgresql/data/
    restart: always

  server:
    container_name: go_server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    depends_on:
      - postgres_db
    links:
      - postgres_db:postgres_db
    volumes:
      - app_logs:/app_logs
    restart: on-failure

  frontend-builder:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app  # Mount the build directory to the container
    command: sh -c "GOARCH=wasm GOOS=js go build -o web/app.wasm && go build -o frontend && ./frontend"

  nginx:
    build: "./nginx"
    ports:
      - "80:80"
    depends_on:
      - server
    volumes:
      - ./frontend:/usr/share/nginx/html/frontend
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

volumes:
  prod_postgres_data:
  app_logs:
